### ISSUE TITLE
Are 3 separate builtins collection worth having?

### ISSUE THREAD

**Issue by jakobkummerow** [WebAssembly/js-string-builtins#15]
I don't feel strongly about it either way, but I'm not sure whether separating out the "Encoding API" is worth doing. Having these three functions in their own collections:
```
"wasm:text-decoder" "decodeStringFromUTF8Array"

"wasm:text-encoder" "measureStringAsUTF8"
"wasm:text-encoder" "encodeStringIntoUTF8Array"
```
means modules that want to use them must specify `{builtins: ["js-string", "text-decoder", "text-encoder"]}` instead of getting by with just `{builtins: ["js-string"]}`, and modules that don't need them don't really get any benefit from not simply having them included in the "js-string" collection.

Lacking a reason for the separation, I would weakly lean towards the simplicity of putting all functions of this proposal into just one collection.

Does anyone else have thoughts on this?

**Comment by eqrion** [comment]
My reasoning for this was that these functions are from three different interfaces on the global,`String`, `TextEncoder`, and `TextDecoder`, and so that seemed like a decent way to group functions.

I thought about grouping by 'spec' for `js-string` and `encoding`, but I've heard that historically things have moved between specs before and so that's not a good thing to bake into a name.

I'm a little uncomfortable with having these all in a single `js-string` module as these functions are not strictly required to be implemented if the host doesn't expose the encoding interfaces. We could move to a single `js` module, but that might run into some naming collisions in the future.

**Comment by eqrion** [comment]
I think we can close this now that the text-encoder/decoder interfaces were punted to a follow up proposal.
