### ISSUE TITLE
Do we require 'wasm:' prefix in options passed to compile?

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/js-string-builtins#38]
The explainer (and implementations) don't require the 'wasm:' prefix in the compile options.

So you just need: `{ builtins: ['js-string'] }` instead of `{ builtins: ['wasm:js-string'] }`.

However, when importing on the core wasm side, you must use the prefix.

I noticed this when writing the spec and it feels a little odd to me. I could see it being unnecessary if we never have builtins in any other namespace, but it might be safer if we require the prefix.

@ajklein @jakobkummerow Do you have any opinions?

**Comment by ajklein** [comment]
To me this makes sense conceptually: "builtins" implies the "wasm:" prefix (since this argument is part of a call to a Wasm API), so it feels redundant if it had to be included. I'm having trouble thinking of what the value would be in having further namespacing here; why would there be another prefix, ever?

**Comment by eqrion** [comment]
I suppose I'm probably being too paranoid. I can't think of a concrete reason, and if one unexpectedly came up we could always add a different kind of flag on the options which required the prefix.

I'll need to update the spec document to have the notion of the 'import name' and 'options name'. Right now there is no difference.

**Comment by eqrion** [comment]
I updated the spec to match this discussion. There's a separate import name `wasm:js-string` and builtin name for options `js-string`.
