### ISSUE TITLE
Confused about "Reading from the imports object requires knowing the keys"

### ISSUE THREAD

**Issue by bakkot** [WebAssembly/js-string-builtins#5]
... Why? You can do `Object.keys(x)` or [if you want things from the prototype] the equivalent of `for (x in y)`. And sure, that might throw if the user has provided a Proxy with a throwy `keys` traps, but... so what? Why bother worrying about that?

**Comment by eqrion** [comment]
The issue is if you're trying to have parity with how the [JS-API spec handles import objects](https://webassembly.github.io/spec/js-api/index.html#read-the-imports). In the existing JS-API it does a property get driven by the imports section of the module.

So yes, we could define a different way of reading an import object for compile-time imports, such as the ones you propose. See #2 for one using the iterator protocol.

I should note too that proxies are actually used as import objects today in real-world code. We probably don't need to support them with compile-time imports, but the reason I proposed the array based imports objects was so that it had a different shape to really emphasize it was interpreted differently by the API.

**Comment by eqrion** [comment]
As of https://github.com/WebAssembly/js-string-builtins/pull/8 there are no more compile-time imports.
